# YAML configuration script

name: btsettle_simulations

data:
  grid_name: "BT-Settl"
  files: [""]
  instruments : ["CRIRES_50k"]
  orders: [1]

outdir : output/

plotdir : plots/

# The parameters defining your raw spectral library live here.
grid:
  raw_path: "/home/jneal/Phd/data/PHOENIX-ALL/PHOENIX/"
  hdf5_path: "/home/jneal/Phd/Codes/companion_simulations/starfish/libraries/PHOENIX_CRIRES_50k.hdf5"
  btsettle_raw: "/home/jneal/Phd/data/PHOENIX-ALL/BT-SETTL/"
  btsettle_hdf5_path: "/home/jneal/Phd/Codes/companion_simulations/starfish/libraries/BTSETTLE_CRIRES_50k.hdf5"
  parname: ["temp", "logg", "Z"]
  key_name: "t{0:.0f}g{1:.1f}z{2:.1f}" # Specifies how the params are stored
  # in the HDF5 file
  parrange: [[2200, 7000], [3.0, 6.0], [-1.5, 1.5]]
  wl_range: [20700, 21000]
  buffer: 50. # AA


chunk_ID: 0
spectrum_ID: 0
instrument_ID: 0


sim_grid:
    gammas: [-20, 20, 1]  # (start, stop, step)
    rvs: [-20, 20, 1]
    alphas: [0.01, 0.25, 0.005]
    teff1: None
    teff2: None
    feh_1: None
    feh_2: None
    log_1: None
    log_2: None
    arb_norm: [0.95, 1.05, 0.02]   # Arbitrary normalization inside chisquare

paths:
    parameters: "/home/jneal/Phd/data/parameter_files/"
    spectra: "/home/jneal/.handy_spectra/"
    output_dir: "Analysis/"