language: python
python:
    - 3.6
    - 3.7
#    - 3.8

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.cache/pip

install:
  - apt-get install libfreetype6-dev
  - apt-get install libpng12-dev
  - source activate test-environment
  - travis_retry pip install -r test_requirements.txt
  - travis_retry pip install -r requirements.txt
  - python setup.py install

build:
  ci:
    - cp tests/config.yaml .

    # Create folders for test and code coverage
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage

    # Run test and code coverage and output results to the right folder
    - pytest --junitxml=shippable/testresults/nosetests.xml
    - pytest --cov=. --cov-report=xml:shippable/codecoverage/coverage.xml --durations=10
    # - pytest --cov=. --cov-report term-missing

# after_success:
  #- coveralls -i
  #- codeclimate-test-reporter
  #- coverage xml -i
  #- python-codacy-coverage -r coverage.xml
