sudo: true
language: python
dist: xenial
services:
  - xvfb
  
python:
    - "3.5"
    - "3.6"

matrix:
  fast_finish: true
  include:
    - python: 3.7
      sudo: true    # travis-ci/travis-ci#9069

cache:
  directories:
    - $HOME/.cache/pip

install:
  - travis_retry pip install -r test_requirements.txt
  - travis_retry pip install -r requirements.txt

# Install Starfish
  - cd $HOME
  - travis_retry git clone https://github.com/iancze/Starfish.git
  - cd Starfish
  - travis_retry pip install -r requirements.txt
  - python setup.py build_ext --inplace
  - python setup.py develop

  # Now install companion simulations
  - cd $TRAVIS_BUILD_DIR               # Return to original directory
  - python setup.py install

  - cp tests/config.yaml .

script:
  -  pytest --cov=. --cov-report term-missing

after_success:
  - coveralls -i
  - codeclimate-test-reporter
  - coverage xml -i
  - python-codacy-coverage -r coverage.xml
