language: python
python:
    - "3.5"
    - "3.6"

before_install:
  # http://conda.pydata.org/docs/travis.html
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
       wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
       wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda config --add channels conda-forge
# command to install dependencies
install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy astropy matplotlib numba llvmlite multiprocess ephem tqdm joblib
  - source activate test-environment
  - pip install -r requirements.txt
  - python setup.py install
  # Test requirements
  - pip install pytest pytest-cov hypothesis python-coveralls codeclimate-test-reporter
  # Clone spectrum_overload
  - git clone https://github.com/jason-neal/spectrum_overload.git
  - cd spectrum_overload
  - python setup.py install
  - cd ..
  # clone Starfish
  - conda install h5py cython pyyaml scikit-learn emcee corner
  - git clone https://github.com/iancze/Starfish.git
  -  cd Starfish
  - python setup.py build_ext --inplace
  - python setup.py install
  - rm tests -r -f     # stop starfish tests running
  - cd ..
# command to run tests
script:
    pytest --cov=utilities --cov-report term-missing --durations 5

after_success:
  - coveralls
  - codeclimate-test-reporter
