sudo: true
language: python
dist: xenial
services:
  - xvfb
  
python:
    - "3.6"
    - "3.7"
#    - "3.8"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - travis_retry pip install -r test_requirements.txt
  - travis_retry pip install -r requirements.txt

  # Now install companion simulations
  - python setup.py install

  - cp tests/config.yaml .

script:
  -  pytest --cov=. --cov-report term-missing

after_success:
  - coveralls -i
  - codeclimate-test-reporter
  - coverage xml -i
  - python-codacy-coverage -r coverage.xml
