sudo: true
language: python
python:
    - "3.5"
    - "3.6"

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial  # Required for Python 3.7
      sudo: true    # travis-ci/travis-ci#9069


cache:
  directories:
    - $HOME/.cache/pip

install:
  - travis_retry pip install -r test_requirements.txt
  - travis_retry pip install -r requirements.txt

# Install Starfish
  - cd $HOME
  - travis_retry git clone https://github.com/iancze/Starfish.git
  - cd Starfish
  - travis_retry pip install -r requirements.txt
  - python setup.py build_ext --inplace
  - python setup.py develop

  # Now install companion simulations
  - cd $TRAVIS_BUILD_DIR               # Return to original directory
  - python setup.py install

  - cp tests/config.yaml .

before_script:  # configure headless display for matplotlib backend
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3  # give xvfb some time to start

script:
  -  pytest --cov=. --cov-report term-missing

after_success:
  - coveralls -i
  - codeclimate-test-reporter
  - coverage xml -i
  - python-codacy-coverage -r coverage.xml
